
[main]
name = "hpge.realtime"
triggers = ["every-minute 03"]

[logger.me]
path="D:/scada/logs/hpge/{$month}"
filename="hpge-{$date}.log"


[action.main]
type="mysql_exec"
mysqlconnection="mysqlconnection"
sql = "select * from hpge_rec where time> '{$today}' and status=0 order by time desc limit 1;"
return = "result_set"
logto="me"
next = "upload"
exit_at = "len({@result_set}) == 0"


[action.upload]
type = "http_post_file"
param0 = "{@result_set.0.Path}"
url="http://{$host}:1024/d/upload/{$hpge_device_id}?fileType=hpge&sid={@result_set.0.Sid}&fileName={@result_set.0.Path|filename}"
return = "post_result"
content_type = "json"
next = "transform"


[action.transform]
type="resultset_to_form"
key_value_attributes = [
	["fileLink", "{@post_result.data.fileLink}"],
    ["dataTime", "{@result_set.0.Time|unixtime}"],
    ["sid", "{@result_set.0.Sid}"],
    ["beginTime", "{@result_set.0.StartTime|unixtime}"],
    ["endTime", "{@result_set.0.EndTime|unixtime}"],
    ["fileName", "{@post_result.data.fileName}"],
    ["fileType", "{@post_result.data.fileType}"]
    ]
param0 = "result_set"
return = "form"
next = "commit"


[action.commit]
type = "http_post"
param0 = "form"
next = "update"
logto="me"
url="http://{$host}:1024/d/send/{$hpge_device_id}"


# 更新数据库状态
[action.update]
type="mysql_exec"
mysqlconnection="mysqlconnection"
sql = "update hpge_rec set Status=1 where Id={@result_set.0.Id};"
return = "update_result"
next = "get_nuclides"
logto="me"


[action.get_nuclides]
type="mysql_exec"
mysqlconnection="mysqlconnection"
sql = "select * from hpge_nuclide_rec where Sid='{@result_set.0.Sid}';"
return = "nuclides_result"
next="transform2"
logto="me"
exit_at = "(len({@nuclides_result}) == 0) or ('{@result_set.0.Path}'.endswith('spe'))"



[action.transform2]
type="resultset_to_form"
key_value_attributes = [
	["nuclide", "{@nuclides_result.@i.Nuclide}"],
    ["activity", "{@nuclides_result.@i.Activity}"],
    ["sid", "{@result_set.0.Sid}"],
    ["dataTime", "{@result_set.0.Time|unixtime}"]
    ]
param0 = "nuclides_result"
return = "form2"
next = "send_nuclides"
logto="me"


[action.send_nuclides]
type = "http_post"
param0 = "form2"
next = ""
logto="me"
url="http://{$host}:1024/d/send/{$hpge_nuc_device_id}"






