

[action.transform]
type = "resultset_to_form"
key_value_attributes = [
    ["humidity", "{@result_set.@i.Humidity}"],
    ["pressure", "{@result_set.@i.Pressure}"],
    ["temperature", "{@result_set.@i.Temperature}"],
    ["windSpeed", "{@result_set.@i.Windspeed}"],
    ["direction", "{@result_set.@i.Direction}"],
    ["raingauge", "{@result_set.@i.Raingauge}"],
    ["rainSpeed", "{@result_set.@i.Rainspeed}"],
    ["isRain", "{@result_set.@i.IfRain}"],
    ["dewpoint", "{@result_set.@i.Dewpoint}"],
    ["dataTime", "{@result_set.@i.Time|unixtime}"]
    ]
    
param0 = "result_set"
return = "form"
logto = "{@@logger}"
next = "post"

[action.post]
type = "http_post"
url = "http://{$host}:1024/d/send/{$weather_device_id}"
param0 = "form"
next = ""